In [16]:
import pandas as pd
import numpy as np
import os

In [18]:
df = pd.read_csv('data.csv', encoding='ISO-8859-1')

In [19]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [22]:
df_clean = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)].copy()

In [27]:
df_clean['revenue'] = df_clean['UnitPrice']*df_clean['Quantity']

In [28]:
df_clean['revenue']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: revenue, Length: 530104, dtype: float64

In [31]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 530104 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    530104 non-null  str
 1   StockCode    530104 non-null  str
 2   Description  530104 non-null  str
 3   Quantity     530104 non-null  int64
 4   InvoiceDate  530104 non-null  str
 5   UnitPrice    530104 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      530104 non-null  str
 8   revenue      530104 non-null  float64
dtypes: float64(3), int64(1), str(5)
memory usage: 40.4 MB

In [32]:
df_clean.describe()

            Quantity      UnitPrice     CustomerID        revenue
count  530104.000000  530104.000000  397884.000000  530104.000000
mean       10.542037       3.907625   15294.423453      20.121871
std       155.524124      35.915681    1713.141560     270.356743
min         1.000000       0.001000   12346.000000       0.001000
25%         1.000000       1.250000   13969.000000       3.750000
50%         3.000000       2.080000   15159.000000       9.900000
75%        10.000000       4.130000   16795.000000      17.700000
max     80995.000000   13541.330000   18287.000000  168469.600000

In [26]:
df_clean.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,revenue
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,14.85